% MVCGPDSTUTORIAL Demonstration of mvcgpds
%%
filep = mfilename('fullpath');
[pathstr, namestr] = fileparts(filep);
cd(pathstr);
addpath(genpath(pwd));
%cd('../..');
%%
fprintf(1, ['\n\n', ...
            ' # Example of running the mvcgpds on the toy dataset:\n', ...
                ' *** Dynamics: \n', ...
                ' >> experimentNo = 3;\n', ...
                ' >> initial_X = ''concatenated'';\n', ...
                ' >> initVardistIters = 600; \n', ...
                ' >> itNo = 1000;\n', ...
                ' >> dynamicKern = {''rbf'', ''white'', ''bias''}; \n', ...
                ' >> dynamicsConstrainType = {''time''};\n', ...
            ' >> demToyMvcgpds1\n']);
%pause
clear; close all;
initial_X = 'concatenated';
dynamicKern = {'rbf', 'white', 'bias'}; % SEE KERN toolbox for kernels\n', ...
% dynamicKern = {'rbf', 'white'};
dynamicsConstrainType = {'time'};

demToyMvcgpds1;

fprintf('\n The End !\n');
